version: '3.1'

services:

#  db:
#    image: postgres:10.1
#    environment:
#      POSTGRES_PASSWORD: Passw0rd
#    ports:
#      - "5432:5432"
#    networks:
#      - backend
#    volumes:
#      - pgdata:/var/lib/postgresql/data/

  web:
    build: ./web/
    ports:
      - "8000:8000"
    volumes:
      - ./web:/code    # mounts ./web in host to /code in container
    command: django-admin startproject my_site .
#    networks:
#      - backend
#    depends_on:
#      - db

#volumes:
#  pgdata:

#networks:
#  backend: